sudo: required
services:
  - docker

before_install:
  - docker build -t xorowieox/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true xorowieox/docker-react npm run test
deploy:
  edge: true 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "rowie"
  env: "Rowie-env"
  bucket_name: "elasticbeanstalk-us-east-1-967195537723"
  bucket_path: "react-app"
  on:
    branch: master
  access_key_id: AKIA6CMKYWE5WTIDCQGY
  secret_access_key: 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
